# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matrix_power <- function(m, power, tol, k) {
    .Call('_SlimPosition_matrix_power', PACKAGE = 'SlimPosition', m, power, tol, k)
}

